### PR TITLE
hotfix (infra): added execution permissions for gh actions

### PR DESCRIPTION
**Pull request by MichielTukker**

### CODE REVIEW

**Comment by MichielTukker** [comment]
All actions run,  but currently fail due to code issues (missing docstrings, missing type annotations,  failing code coverage metric)

**Comment by vanmeerkerk** [comment]
Ok

**Review by vanmeerkerk — APPROVED** [review]
Approved. However, I do not fully understand where you ahve added the "execution permission for GH actions".

**Comment by MichielTukker** [comment]
Githuh doesn't show the change in file permissions, maybe Fork does?

You can change it with this command: https://stackoverflow.com/a/40979016

It's necessary to run scripts on linux

**Pull request merged**
